'\" t
.\"     Title: tvpvrd
.\"    Author: Johan Persson <johan162@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/26/2009
.\"    Manual: http://sourceforge.net/projects/tvpvrd/docs/
.\"    Source: http://sourceforge.net/projects/tvpvrd/ @VERSION@
.\"  Language: English
.\"
.TH "TVPVRD" "1" "11/26/2009" "http://sourceforge\&.net/proje" "http://sourceforge\&.net/proje"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
tvpvrd \- TV Personal Video Recorder Server/Daemon
.SH "SYNOPSIS"
.HP \w'\fBtvpvrd\fR\ 'u
\fBtvpvrd\fR [options\&.\&.\&.]
.SH "DESCRIPTION"
.PP
The
\fBtvpvrd\fR(1)
command starts a video recording server that will make use of one or more installed TV\-Capture cards and, following a specified schedule, will record broadcasted and encoded streams from the capture card to disk\&. In affect a digital version of a programmable VHS\&.
.PP
The original stored HW encoded file (from the capture card) can then be automatically transcoded (using
\fBffmpeg\fR(1)
) to a more efficient format\&. The specific details on both the initial HW encoder settings as well as the transcoding options are bundled in a \'profile\'\&.
.PP
Each recording is done using one (or multiple) profiles\&. Each recording will always have at least one profile\&. By default the distribution includes four profiles \'high\', \'normal\', \'low\', \'mobile\'\&. Additional profiles can easily be added by the user\&. A profile is specified in a traditional ini\-file text file stored under the \'profiles\' directory\&. Each setting in the profile is well documented in the profiles\&. The settings are also described in
\fBtvpvrd\fR(5)
.PP
The primary interface to the server is via a TCP/IP connection to the server running \'\fItvpvrd\fR\' via a dedicated port (by default 9300)\&. The server is controlled via a simple (but efficient) command language which allows manipulation of future recordings and various other administrative tasks\&. All commands are extensively described in the section \'Command language\' below\&.
.PP
Each recording is done using one (or multiple) profiles\&. Each recording will always have at least one profile, the primary profile\&. In this way it is possible to create multiple transcoded versions of one recording, for example one high quality version for viewing on a computer and one low quality versions for viewing on a mobile device\&.
.PP
Additional profiles can easily be added by the user\&. A profile is specified in a traditional ini\-file text file stored under the \'profiles\' directory\&. For details on the profile file settings see
\fBtvpvrd\fR(5)
.PP
The recordings specified are stored in a database which is a plain text file in XML format (UTF\-8 encoded)\&.
.PP
Recorded and transcoded files are stored in a predefined directory structure\&. The base directory for this directory structure is defined in the ini\-file\&.
.SH "ARGUMENTS"
.PP
The following arguments are supported
.PP
\fB\-d\fR, \fB\-\-daemon\fR [\fIy\fR|\fIn\fR]
.RS 4
Determine whether the server should be disconnected from the controlling terminal (a\&.k\&.a\&. running as a daemon)\&. If the server is run as a daemon the logfile cannot be \'\fIstdout\fR\'\&. This command line option will override the \'\fIdaemon\fR\' setting in the ini\-file\&. The default setting is to run as a daemon\&.
.RE
.PP
\fB\-f\fR, \fB\-\-xmldbfile\fR filename
.RS 4
Use the specified file as the database file where all the specified recordings are stored in XML format\&. This command line option will override the \'\fIxmldbfile\fR\' setting in the ini\-file\&. The default location is \'<dataroot>/xmldb/tvpvrd_db\&.xml\'
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a short help and exit\&.
.RE
.PP
\fB\-i\fR, \fB\-\-inifile\fR filename
.RS 4
Use the specified file as configuration file\&. This will override the location specified at compile time\&. The default location is \'/etc/tvpvrd/tvpvrd\&.conf\'
.RE
.PP
\fB\-l\fR, \fB\-\-logfile\fR filename
.RS 4
Define what logfile to use\&. Two special names can be used
stdout
which will cause the log to be written to the
\fIstdout\fR
and
syslog
which will cause the logs to be written using the default system log\&. This command line option will override the \'\fIlogfile\fR\' setting in the ini\-file\&. The default location is \'/tmp/tvpvrd\&.log\'
.RE
.PP
\fB\-p\fR, \fB\-\-port\fR \fInnnn\fR
.RS 4
Specify TCP/IP port number\&. This will override the \'\fIport\fR\' setting in the ini\-file\&. By default the distribution uses port 9300\&.
.RE
.PP
\fB\-V\fR, \fB\-\-verbose\fR [\fI0\fR|\fI1\fR|\fI2\fR]
.RS 4
Log verbosity level\&. 0 will only log error messages, 1 will log error and info messages, 2 will log errors, info and additional low volumne debug messages, 3 will also log high volume debug messages\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print program version information and exit\&.
.RE
.PP
\fB\-x\fR, \fB\-\-xawtvrc\fR filename
.RS 4
Use the specified file to read the station names\&. The station name file maps the standardized frequency channel names to the more commonly used station names\&. See the section "Stations, channels and frequencies" below for more information\&. This will override the setting in the ini\-file\&. The default location is \'/etc/X11/xawtvrc\'
.RE
.SH "STARTING AND STOPPING THE SERVER"
.PP
While strictly speaking not necessary the server should normally be started by the root user\&. As soon as the server doesn\'t need root privileges it will switch to run as the user specified in the ini\-file, by default this is the user
\fItvpvrd\fR\&. This user should for security reasons not be the \'root\' user\&. This user should be a system user without login shell\&. Such a user can normally be created by running the command \'\fIuseradd\fR\'\&. (If the server is installed via the RPM package this user will be automatically created)
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
$> useradd \-r tvpvrd
.fi
.if n \{\
.RE
.\}
.PP
To start the server as root the simplest way is to just call
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
$root> tvpvrd
.fi
.if n \{\
.RE
.\}
.PP
In order to stop the server and allow it to do a clean shutdown the SIGHUP (or SIGSTOP) signal should be sent to the process running the server (assuming tvpvrd has been started as a daemon)\&. The distribution includes a simple script \'stop\-tvpvrd\' which will read the server pid from \'/var/run/tvpvrd\&.pid\' and send the SIGHUP signal\&.
.PP
In order to stop the server first switch to root user and then use the command
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
$root> stop\-tvpvrd
.fi
.if n \{\
.RE
.\}
.PP
To manually kill the daemon process one can send the SIGHUP signal via the \'\fIkill\fR\'command as
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
$> kill \-SIGHUP <pid>
.fi
.if n \{\
.RE
.\}
.PP
where <pid> is the process id of the
\fItvpvrd\fR
daemon\&. Use \'ps xa\' to find the pid or if the server was started as root look in the file \'/var/run/tvpvrd\&.pid\'
.PP
When the server is shutdown the DB will be updated and depending on the "Kill transcoding flag" (see the
\fB\-ktf\fR
command) any on\-going transcodings will be shutdown\&. Any potential ongoing recordings will be aborted and the recordings up to the time the recording is shutdown will be left in the \'<data\-dir>/vtmp\' directory and must be removed manually\&.
.SH "CONNECTING TO THE SERVER"
.PP
Once the server is running the easiest way to connect to the server is by using the \'\fItelnet\fR\' program\&. Assuming that the
\fItvpvrd\fR
server is running on the localhost the following command will connect to the server (assuming the default port 9300 has not been changed in the ini\-file (e\&.g\&.
/etc/tvpvrd\&.conf) or by a command line argument)\&.
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
$> telnet localhost 9300
.fi
.if n \{\
.RE
.\}
.PP
After a successful connection the server will reply with a short information message\&. To help identify the server the first line returned is always \'!TVPVRD!\'\&. The full returned information message at the connection time is
.sp
.if n \{\
.RS 4
.\}
.nf
!TVPVRD!
Welcome to TVPVR\-Server 1\&.0\&.0 (Nov 19 2009)
You are user number 1 out of 2 allowed\&.
Type \'exit\' to disconnect\&.
Type \'h\' to list available commands\&.
Connection will be closed after 30 min of inactivity\&.
.fi
.if n \{\
.RE
.\}
.PP
If password protection (see section "Security" below) the welcome message is not be shown until the correct password has been specified\&. Instead when password protection is enabled the connection sequence looks like this
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
$> telnet localhost 9300
Password:\fBxxxxxxx\fR
!TVPVRD!
Welcome to TVPVR\-Server 1\&.0\&.0 (Nov 19 2009)
You are user number 1 out of 2 allowed\&.
Type \'exit\' to disconnect\&.
Type \'h\' to list available commands\&.
Connection will be closed after 30 min of inactivity
.fi
.if n \{\
.RE
.\}
.PP
This means that the correct server password has to be given before the welcome message is seen\&. The server is now ready to accept commands on this connection\&.
.SH "THE RECORDING AND TRANSCODING PROCESS"
.PP
The recording process refers to the process of saving the generated MP2 video stream from the capture card to a file\&.
.PP
The transcoding process refers to the re\-coding of the original MP2 video stream to a more efficient format, usually an MP4 container using H\&.264 video codec (the default in the distributed profiles)\&. Depending on the quality settings it is common to see reduction in original file size with 75%
.PP
Unfortunately the transcoding process is extremely CPU\-intensive and with the default settings in the distribution the normal profile will require roughly the same time to transcode as the original play time on a high end machine (as of 2009) \&. In order not to make the machine totally unresponsive the ini\-file specifies a maximum load for a transcoding to start in order not to load the server with too many parallel transcoding processes\&. If the load is too high the transcoding processes will be put in a queue waiting for the load to become acceptable\&.
.PP
Each transcoding process is run with a \'nice\' value of 20\&.
.PP
When a recording is started a temporary directory will be created under \'<data\-dir>/vtmp/vid<n>/\' where <n> is the number of the video card used\&. The name of the temporary directory will be the same as the base name of the recording\&. The MPEG stream is read from the video card and stored in a file in the temporary directory with the same name as the title (converted to lower case) with the suffix "\&.mpg"\&.
.PP
The hardware capture card settings to be used (bitrate, frame size etc\&.) is read from the primary profile (i\&.e\&. the first profile)\&.
.PP
When the recording has stopped the transcoding profile(s) is read and the transcoding is started after a check that the server load is not higher than the maximum allowed load in order to start a transcoding\&. If the load is too high the transcoding is put in a queue of waiting transcodings that will be started when the server load allows the transcoding to start\&. One transcoding will be made for each of the associated profiles of this recording\&.
.PP
As a special case no transcoding will be made if the \'\fIffmpeg\fR\' profile bitrate is set to 0 Mbps in the profile\&. In this case only the original MP2 video file will be kept\&.
.PP
Once a transcoding has finished the resulting MP4 file will be moved to the directory \'<data\-dir>/mp4/<profile>/\' with the same file basename as the title but with the filename suffix "\&.mp4"\&.
.PP
When all the transcodings have been done and if the profile defines that the original MP2 video stream should be kept it is moved to the directory \'<data\-dir>/mp2/\'\&. After that the temporary directory (and the original MP2 file) is deleted\&.
.SH "DIRECTORY STRUCTURE"
.PP
The root directory for where the video files (recordings) are stored is specified in the ini\-file (e\&.g\&. /etc/tvpvrd/tvpvrd\&.conf)\&. Under this root directory the following subdirectories and files are automatically created by the server:
.PP
.PP
<dataroot>/mp2
.RS 4
If the profile specifies that the original MP2 files recorded from the capture card should be saved they are stored under this directory\&.
.RE
.PP
<dataroot>/mp4/<profile>
.RS 4
The transcoded original MP2 files are placed under a subdirectory under MP4 corresponding to the name of the profile used for the transcoding\&.
.RE
.PP
<dataroot>/stats/<profile>\&.stats
.RS 4
The statistics recorded while transcoded is stored in a file corresponding to the name of the profile\&.
.RE
.PP
<dataroot>/vtmp
.RS 4
Temporary video directory used while recording and transcoding is performed\&. Each capture card used has its own subdirectory\&.
.RE
.PP
<dataroot>/xmldb/
.RS 4
The XML file which represents the recordings database is stored under this directory
.RE
.SH "SECURITY"
.PP
In order to prevent unauthorized access to the server the server have a basic password protection\&. This means that a password can be configured to be used before a client can start giving command to the server\&. This is configured in the ini\-file\&. The configuration uses the same password for all clients so the server does not support multiple users/multiple password\&. Since the password is stored in plain text format the configuration file should have restricted access\&. This should not be considered strong security but rather a weak "stop\-messing\-with\-my\-recordings" protection\&.
.PP
The setting whether password should be used or not and the actual password is specified in the ini\-file\&. For more information on the ini\-file see
\fBtvpvrd\fR(5)
.PP
After connecting to the server when the password has been enabled the first string sent back from the server will be
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
Password:
.fi
.if n \{\
.RE
.\}
.sp
.SH "STATIONS, CHANNELS AND FREQUENCIES"
.PP
All TV stations are broadcasted on a local unique frequency\&. The frequency spectrum is divided in internationally standardized fixed width channels\&. A channel is the same as a specified frequency\&. The distance between each assigned frequency is different depending on both the frequency area and the TV standard used\&. This depends on the fact that different TV standard requires different bandwidth\&. This channel division is also different depending on the geographic location\&.
.PP
It is important to realize that these fixed frequencies are assigned according to international standards\&. In each city (and city area) the broadcasting company is then responsible for assigning local stations to appropriate frequency channels\&. This is the difference between station and channel names\&. The channel names have short names with 2 to 5 characters, for example \'SE14\'\&. Even though the frequency division is standardized the exact channel names are not always given with the assigned names\&. For example a broadcasting company might claim (for example on their home page) that the station \'BBC1\' in a certain area can be found on channel \'14\' when they actually should have said that the station can be found on channel \'SE14\' which is the official name of this channel\&.
.PP
To further complicate matters different countries uses different standardized frequency maps\&. The program has built in knowledge of the frequency channels available in the following geographic areas
.PP

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_EUROPEWEST
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_EUROPEEAST
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_FRANCE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_IRELAND
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_ITALY
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_AUSTRALIA
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_NEWZEALAND
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_USBCAST
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
FREQMAP_USCABLE
.RE
.sp
.RE
.PP
Since the program has no way to automatically know which map to use this must be specified in the application ini\-file\&. This map file lists all the defined frequencies and the official name for that country and frequency\&.
.PP
In order to record a specific station the tuner on the capture card must be tuned to the correct frequency channel used by the station we want to record\&. Since it is a lot easier to use the station names, for example "BBC1", than the official name on the frequency channel, e\&.g\&. SE14, the program uses yet another mapping file so it is possible to use station names when recording instead of frequency channels\&.
.PP
In order for maximum re\-use
\fItvpvrd\fR
uses the same format of the station/channel mapping file as is done in \'\fIxawtvrc\fR\'\&. This is a plain text file using ini\-file format\&. In the distribution an example file is included\&. Normally your TV provider provides a channel plan for your area\&. Unfortunately, to make things a bit more difficult some broadcasting company is not following the international naming convention\&.
.PP
If you are already viewing TV on your computer chances are very high that you already have this \'xawtvrc\' ini\-file since it is used by many of the available TV viewing programs\&. Common location for this file is either \'/etc/X11/xawtvrc\' or in your home directory \'\&.xawtvrc\'\&.
.PP
An example of a station\-channel mapping file is shown below (this mapping file happens to be the maps for a large Swedish distributor in the Stockholm region):
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
[Kanal5]
channel = SE11
[Kanal8]
channel = 57
[Kanal9]
channel = S36
[MTV]
channel = SE16
[SVT24]
channel = E10
[SVTB/Kunsk]
channel = SE13
[TV1]
channel = E5
[TV2]
channel = E7
[TV3]
channel = E11
[TV4]
channel = E6
[TV4+]
channel = SE14
[TV6]
channel = E8
.fi
.if n \{\
.RE
.\}
.PP
In some Unix distributions there are automatic frequency scanning helper programs (for example
\fBscantv\fR(1)) which will search through a given frequency map and list all channels where a broadcasting was find (this is identified as a high enough signal strength)\&. For example SuSE distribution have a TV channel scanning setup in the yast2 configuration tool\&. The result of this channel scan is usually stored in a file named \'xawtvrc\'\&. This is usually stored in either \'/etc/X11/xawtvrc\' or in you home directory, usually as \'~/\&.awtvrc\'\&. Of course even if the channel with broadcastings can be found the station names must be manually given\&.
.PP
The somewhat strange name of the map file comes from an ancient TV viewer program under X11 which is called \'xawtv\'\&. For historic reason this name has stayed\&.
.PP
While it is possible to use either the station name or the channel name in a recording there must be a \'xawtvrc\' file in order for the server to start properly\&. If the station file cannot be found an error message will be printed and the server will not start\&.
.PP
The location of this file is normally specified in the ini\-file but the location can also be overridden with command line argument (\fB\-x\fR) when the server is started (see Options) which will override the setting in the ini\-file\&.
.SH "COMMANDS"
.PP
The following is a list and detailed explanation of the commands that are recognized by the server\&. Commands are specified by 1 to 3 letters followed by any necessary arguments\&. It is possible to get more detailed help/information for each command by giving the help command \'h\' followed by the command, e\&.g\&. \'h l\', will give more detailed help on the \'list\' command\&.
.PP
The input and output has a format suitable for both human interactive use as well as a programatically interfacing in order to build a UI that interacts with the server\&.
.PP
.PP
\'\fBh\fR\' \- Help command
.RS 4
Print a summary of all commands available\&.
.RE
.PP
\'\fBv\fR\' \- Version command
.RS 4
Print program version and name as well as the build date\&. The following lines will give information on how the server was compiled\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
tvpvrd 1\&.0\&.0 (Nov 19 2009)
Compiled with Large File Support (files > 2GB)\&.
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBt\fR\' \- Current Time and Date command
.RS 4
Print current time and date on the server where \'tvpvrd\' is running
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
Fri Nov 20 15:51:20 2009
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBs\fR\' \- Server status command
.RS 4
Print a summary of the server status\&. This includes when the tvpvrd was started, how long it has been running for, the current server load, current server time and a list of the clients currently connected to the server\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
   Current time: Fri Nov 20 15:45:04 2009
        Started: Thu Nov 19 14:00:19 2009
         Uptime: 25:44:45
    Server load: 0\&.0 0\&.0 0\&.3
        Clients: #01: 127\&.0\&.0\&.1, Fri Nov 20 15:44:52 2009
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBst\fR\' \- Print profile statistics
.RS 4
Print transcoding statistics for the defined profiles\&. This statistics is gathered for every transcoding made\&. The statistics includes among other things the running time and average size per minute of the original MP2 and the transcoded file\&. The statistics for the transcoding can be used to predict how long time a transcoding will take\&. However since it is highly dependent on the load on the server it can be difficult to accurately predict the needed transcoding time\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
profile_name            : \'normal\'
transcoding_speed       : 44 s transcoded / min
mp2size_1min            : 27\&.5 Mb/min
mp4size_1min            : 6\&.4 Mb/min
comp_ratio              : 4\&.3
total_ttime             : 3481 min
total_mp2time           : 1779 min
total_mp2files          : 31
total_mp4files          : 31
.fi
.if n \{\
.RE
.\}
.sp
The different fields have the following meaning
.PP
\fIprofile_name\fR
.RS 4
The name of the profile that this statistics apply to\&.
.RE
.PP
\fItranscoding_speed\fR
.RS 4
How much play time the server on average can transcode per minute run time of \'ffmpeg\'\&.
.RE
.PP
\fImp2size_1min\fR
.RS 4
The average size of 1 minute play time in the original MP2 file\&.
.RE
.PP
\fImp4size_1min\fR
.RS 4
The average size of 1 minute of play time in the resulting transcoded MP4 size\&.
.RE
.PP
\fIcomp_ratio\fR
.RS 4
The compression ration between the original MP2 size and the MP4 transcoded file\&.
.RE
.PP
\fItotal_ttime\fR
.RS 4
Total running time that has been spent transcoding files\&.
.RE
.PP
\fItotal_mp2time\fR
.RS 4
Total recorded original MP2 time\&.
.RE
.PP
\fItotal_mp2files\fR
.RS 4
Total number of mp2files recorded with this profile\&.
.RE
.PP
\fItotal_mp4files\fR
.RS 4
Total number of transcoded MP4 files with this profile\&.
.RE
.sp
.RE
.PP
\'\fBrst\fR\' \- Reset statistics command
.RS 4
Reset all statistics, i\&.e\&. set all statistics to 0\&.
.RE
.PP
\'\fBvc\fR [\fI0\fR|\fI1\fR|\fI2\fR|\fI3\fR|\fI4\fR]\' \- Video Card information command
.RS 4
Print information on the specified video/capture cards\&. The command will print information of all available cards if no specific card number is specified\&. The information shown is the name of the card, driver and driver version\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
Card 00: Hauppauge WinTV PVR\-350, driver=ivtv v1\&.4\&.1
Card 01: Hauppauge WinTV PVR\-150, driver=ivtv v1\&.4\&.1
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBl\fR\' \- List command
.RS 4
List all upcoming recordings\&.
.sp
Each record is listed with 7 fields\&. Each record starts with a \'[\' and ends with a \']\' character\&. Each field is separated with a bar \'|\'\&. The order of fields are
.sp

.sp
.if n \{\
.RS 4
.\}
.nf
<id#> <station/channel name> <start\-date> <start\-time> <end\-time> <title> <profile>
.fi
.if n \{\
.RE
.\}
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
[160|tv4    |2010\-03\-09|21:00|21:59|House (16/20)                 |@normal]
[135|kanal5 |2010\-03\-11|21:00|21:59|Criminal minds (16/20)        |@normal]
[038|kanal5 |2010\-03\-11|22:00|22:59|Fringe (17/20)                |@normal]
[088|kanal5 |2010\-03\-14|22:25|23:19|Supernatural (18/21)          |@normal]
[161|tv4    |2010\-03\-16|21:00|21:59|House (17/20)                 |@normal]
[136|kanal5 |2010\-03\-18|21:00|21:59|Criminal minds (17/20)        |@normal]
[039|kanal5 |2010\-03\-18|22:00|22:59|Fringe (18/20)                |@normal]
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBls\fR\' \- List stations command
.RS 4
List all defined station names\&. The stations are specified in the
xawtvrc
file and maps station names to channel names\&. When defining the frequency for a recording either the defined station name or channel (frequency) name can be used\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
  SE11: kanal5
    57: kanal8
   S36: kanal9
  SE16: mtv
   E10: svt24
  SE13: svtb/kunsk
    E5: tv1
    E7: tv2
   E11: tv3
    E6: tv4
  SE14: tv4+
    E8: tv6
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBlc\fR [\fI#card\fR]\' \- List all video capture card controls command
.RS 4
This can be considered a low level command of limited use for an end user\&. This command will list all user controllable controls that can be adjusted on the specified video card\&. This is directly related to the discovered \'v4l2\' interfaces\&. Since the output is quite long we do not include any example output here\&.
.RE
.PP
\'\fBn\fR\' \- Next recording command
.RS 4
List the immediate next recording(sw) scheduled for the available video card(s)\&. The first number in parenthesis is how long time until the recording will start\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
(01:37) : [002|tv3    |2009\-11\-20|18:00|18:59|NCIS_18 (02/20)               |@normal]
(52:37) : [143|tv4    |2009\-11\-22|21:00|22:00|Shooter 1                     |@normal]
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBo\fR\' \- Ongoing recordings command
.RS 4
List all ongoing recording in ordinary list format for all video cards\&. If no recordings are ongoing the output will show "None"
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
Video #0: [175|tv1    |2009\-11\-20|16:26|16:27|tv1_20091120_1626             |@normal]
Video #1: None\&.
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBot\fR\' \- Ongoing transcodings command
.RS 4
List all ongoing transcodings\&. The output format is
.sp

.sp
.if n \{\
.RS 4
.\}
.nf
<#id> <start\-time> <(duration)> <filename> <profile>
.fi
.if n \{\
.RE
.\}
.sp
The start time identifies when the transcoding was started and duration shows for how long the transcoding has been running\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
[#00|16:27|(00:00)|tv1_20091120_1626\&.mpg              |normal]
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBotl\fR\' \- Ongoing transcoding long command
.RS 4
List all ongoing transcoding in long format which includes the detailed \'ffmpeg\' command used which is printed on the second line\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
[#00|16:27|(00:00)|tv1_20091120_1626\&.mpg              |normal]
(cmd: /usr/bin/ffmpeg \-v 0 \-i tv1_20091120_1626\&.mpg \-threads 0 
\-vcodec libx264 \-vpre normal \-b 700k \-bt 1000k  \-croptop 8 \-cropbottom 8 
\-cropleft 2 \-cropright 2  \-acodec copy \-ab 196k  \-y  
tv1_20091120_1626\&.mp4 > /dev/null 2>&1)
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBkt\fR\' \- Kill allgoing transcoding command
.RS 4
Stop all ongoing transcodings\&.
.RE
.PP
\'\fBktf\fR [\fIy\fR|\fIn\fR]\' \- Kill transcoding flag set/unset command
.RS 4
The kill transcoding flag determines whether or not the transcoding processes should be killed when the server is stopped\&. By default all transcoding processes are killed when the tvpvrd server is killed\&. By setting this flag to \'n\' (No) the transcoding processes will be allowed to keep running after the server is stopped\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
ktf n
killflag=n
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBz\fR\' \- Display all ini\-file settings command
.RS 4
This will list all settings made in the ini\-file as well as the location of the used ini file\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
datadir                 : /data/pvr
logfile                 : /tmp/tvpvrd\&.log
inifile_name            : /etc/tvpvrd/tvpvrd\&.conf
xmldbfile_name          : /data/pvr/xmldb/tvpvrd_db\&.xml
max_video               : 2
max_entries             : 1024
max_clients             : 2
client_idle_time        : 1800s
port                    : 9300
time_resolution         : 3s
video_buffer_size       : 200000 (0\&.2MB)
default_recording_time  : 00:59 (h:min)
xawtv_station file      : /etc/X11/xawtvrc
default_profile         : normal
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fBzp\fR [\fI@profile\fR]\' \- Display profile information command
.RS 4
Display information on the settings of the specified profile\&.
.sp
Output example:
.sp
.if n \{\
.RS 4
.\}
.nf
                     name: normal
ENCODER:
            video_bitrate: 3400000
       video_peak_bitrate: 4000000
           audio_sampling: 44\&.1
            audio_bitrate: 192
                   aspect: 4x3
                     size: vga
FFMPEG:
            video_bitrate: 700
       video_peak_bitrate: 1000
                   vcodec: libx264
                     vpre: normal
                     pass: 1
                   acodec: copy
            audio_bitrate: 196
               video_size:
                     crop: (l=2, r=2, t=8, b=8)
     ffmpeg_extra_options:
           file_extension: \&.mp4
.fi
.if n \{\
.RE
.\}
.RE
.PP
\'\fB!\fR [\fI#videocard\fR]\' \- Stop recording on specified video card
.RS 4
Stop the recording on the specified video card\&. The aborted recording will be left in the \'<data\-dir>/vtmp/vid<n>/\' directory and must be manually removed\&.
.RE
.PP
\'\fBu\fR\' \- Update database file command
.RS 4
Force update of the database file from memory\&.
.RE
.PP
\'\fBx\fR\' \- View XML database command
.RS 4
View the current specified recordings in XML DB format\&. See
\fBtvpvrd\fR(5)
for details about the format\&.
.RE
.PP
\'\fBa\fR\' \- Add recording command
.RS 4
Add new recording\&. The date/time logic is fairly complete and will for example correctly handle date crossings when recording starts and ends on different sides on the midnight\&. For all recording formats both title and profile might be omitted\&. In such case the title will be constructed from the station/channel name and the start date/time\&.
.sp
If no end time is given the recording will have the default recording length as defined in the ini\-file\&. In the distribution this is set to 0:59 hours\&.
.sp
For all variants the start and end time is specified as
.sp

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIhh\fR
[:\fImm\fR
[:\fIss\fR]]
.RE
.RS 4
.sp
The maximum length for one recording is 4 hours in order to keep the file size manageable\&.
.sp
The primary formats are described below\&. The syntactic element used have the following meaning:
.sp
<ch> = Channel or station name
.sp
<starttime> = Time for recording start
.sp
<endtime> = Time for recording end
.sp
<title> = Title of recording\&. This will also be used as the filename of the resulting file\&. Note that the filename will always be converted to lower case\&.
.sp
<@profile> = Name of the profile(s) to be used to the recording\&. Up to 4 profiles can be specified for each recording\&.
.sp
The three main variants of the add command are:
.PP
\fIa <ch> <starttime> [<title>] [<@profile]\fR
.RS 4
Specification of only start time\&. The end time will match the default recording length as specified in the ini\-file\&.
.sp
If the start time is after the current time the date will be assumed to be today\&. If the time is earlier than the current time the date is assumed to be tomorrow\&.
.sp
If no title is specified the title will be constructed from the station/channel name and the start date and time\&.
.sp
If no profile is specified then the default profile specified in the ini\-file will be used\&.
.RE
.PP
\fIa <ch> <starttime> <endtime> [<title>] [<@profile]\fR
.RS 4
Specification of both start and end time\&.
.sp
If the start time is after the current time the date will be assumed to be today\&. If the time is earlier than the current time the date is assumed to be tomorrow\&.
.sp
If no title is specified the title will be constructed from the station/channel name and the start date and time\&.
.sp
If no profile is specified then the default profile specified in the ini\-file will be used\&.
.RE
.PP
\fIa <ch> <startdate> <starttime> <endtime> [<title>] [<@profile]\fR
.RS 4
Full date and time specification\&. The date can be specified as
.sp

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIyyyy\-mm\-dd\fR
.sp
Numerical date yyyy=year, mm=month [1\-12], dd=day [1\-31]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[\fItoday\fR|\fItomorrow\fR|\fImon\fR|\fItue\fR|\fIwed\fR|\fIthu\fR|\fIfri\fR|\fIsat\fR|\fIsun\fR]
.sp
Relative date from today\&. The weekday name refers to the coming 7 days\&. If the same day as the current day is given then this refers to 7 days in the future\&.
.RE
.RS 4
.sp
If the start time is after the current time the date will be assumed to be today\&. If the time is earlier than the current time the date is assumed to be tomorrow\&.
.sp
If no title is specified the title will be constructed from the station/channel name and the start date and time\&.
.sp
If no profile is specified then the default profile specified in the ini\-file will be used\&.
.RE
.sp
\fBExamples\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
a bbc1 19:30
.fi
.if n \{\
.RE
.\}
.sp
Start a recording at 19:30 on station BBC1 which will have the default duration, default title and profile\&.
.sp
.if n \{\
.RS 4
.\}
.nf
a bbc1 tue 19:30 News
.fi
.if n \{\
.RE
.\}
.sp
Start a recording at 19:30 on station BBC1 the coming Tuesday which will have the default duration with title \'News\' and profile\&.
.sp
.if n \{\
.RS 4
.\}
.nf
a bbc1 19:30 21:15 News 
.fi
.if n \{\
.RE
.\}
.sp
Start a recording at 19:30 which will last until 21:15 on BBC1 with title set to "News"\&. The default profile will be used\&.
.sp
.if n \{\
.RS 4
.\}
.nf
a ch4 wed 22:00 23:45 The Movie 
.fi
.if n \{\
.RE
.\}
.sp
Start a recording the coming Wednesday at 22:00 until 23:45 on CH4 with title "The Movie"\&. The default profile will be used\&.
.sp
.if n \{\
.RS 4
.\}
.nf
a bbc2 tomorrow 18 20 "World in Focus" @mobile 
.fi
.if n \{\
.RE
.\}
.sp
Start a recording tomorrow at 18:00 until 20:00 on bbc2 with title "World in Focus"\&. Using the mobile profile\&.
.sp
.if n \{\
.RS 4
.\}
.nf
a bbc2 tomorrow 18 20 "World in Focus" @mobile @normal
.fi
.if n \{\
.RE
.\}
.sp
Start a recording tomorrow at 18:00 until 20:00 on bbc2 with title "World in Focus"\&. Using both the mobile and the normal profile\&.
.RE
.PP
\'\fBq\fR\' \- Quick recording command
.RS 4
Add new recording that will start immediately\&. This is basically the same as a simplified \'\fIa\fR\' command where the start time and date is always the current date and time\&.
.sp
The format of the command are
.PP
\fIq <ch> [<duration>] [<title>] [<@profile]\fR
.RS 4
The recording will start within a few seconds (depending on the resolution time specified in the ini\-file) and will last for the duration specified\&. If no duration is specified the default duration time will be used\&. The duration is specified with hours and minutes as
.sp
\fIhh:mm\fR
.sp
If no title is specified the title will be constructed from the station/channel name and the start date and time\&.
.sp
If no profile is specified then the default profile specified in the ini\-file will be used\&.
.RE
.sp
\fBExamples\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
q bbc2  
.fi
.if n \{\
.RE
.\}
.sp
Start a recording immediately on bbc2 using the default duration, title and profile\&.
.sp
.if n \{\
.RS 4
.\}
.nf
q bbc2 1:30 
.fi
.if n \{\
.RE
.\}
.sp
Start a recording immediately on bbc2 with duration 1 hour 30 minutes, using default title and default profile\&.
.sp
.if n \{\
.RS 4
.\}
.nf
q bbc2 News 
.fi
.if n \{\
.RE
.\}
.sp
Start a recording immediately on bbc2 with default duration using the title "News" and default profile\&.
.sp
.if n \{\
.RS 4
.\}
.nf
q ch4 1:45 Newsfocus @high  
.fi
.if n \{\
.RE
.\}
.sp
Start a new recording on station \'ch4\' with title \'Newsfocus\' using the \'high\' profile\&.
.RE
.PP
\'\fBar\fR\' \- Add repeated command
.RS 4
Add a new repeated recording \&. The syntax is identical to the normal add command with the exception of the first two arguments which indicates the type of recurrence and the number of repeated occurrences\&. The full syntax is:
.PP
\fIar <repeat\-type> <repeat\-count> <normal add arguments>\fR
.RS 4
.sp
\fIrepeat\-type\fR
.sp
This specifies how often the repetition should be done\&. This can be specified as one of the following arguments:
.sp

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\'d\' \- Repeat daily (can also be specified as \'1\')
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\'w\' \- Repeat weekly (can also be specified as \'2\')
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\'m\' \- Repeat monthly (can also be specified as \'3\')
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\'f\' \- Repeat Monday to Friday (can also be specified as \'4\')
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\'s\' \- Repeat every Saturday to Sunday (can also be specified as \'5\')
.RE
.RS 4
.sp
\fIrepeat\-cnt\fR
.sp
This specifies the number of repeated recordings\&.
.RE
.sp
Since only one title is given for multiple recording the titles will be mangled with the recording date and time\&. In the recording list the title will usually be shown as "Base title (xx/yy)" where xx is the sequence number and yy is the total number of recordings in this sequence\&.
.sp
Examples:
.sp
.if n \{\
.RS 4
.\}
.nf
ar f 10 bbc1 18 18:30 News
.fi
.if n \{\
.RE
.\}
.sp
Start recording every Mon\-Tue at BBC1 between 18:00 and 18:30
.sp
.if n \{\
.RS 4
.\}
.nf
ar w 20 tv1 tue 21:15 22:10 John Adams
.fi
.if n \{\
.RE
.\}
.sp
Start a recording once a week on Tuesday evening at 21:15 until 22:10 with base title "John Adams"\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ar s 10 BBC1 01:00 02:30 Night movie 
.fi
.if n \{\
.RE
.\}
.sp
Add a recording every weekend night between 01:00 and 02:30 with the base title "Night movie"\&. The recording will be done for the next 5 weekends (2 recordings each weekend)\&.
.RE
.PP
\'\fBd\fR \fInnn\fR\' \- Delete specified recording
.RS 4
Delete specified recording\&.
\fInnn\fR
is the recoding id shown when a recording is added or by the list command\&. If the identified recording is part of a recurrent sequence the other recordings in the same sequence are untouched\&.
.RE
.PP
\'\fBdr\fR \fInnn\fR\' \- Delete all repeated recordings
.RS 4
Delete all repeated recording that are part of the same repeating sequence as the id of the recording specified\&.
.RE
.PP
\'\fBrp\fR\' \- Refresh profiles command
.RS 4
This command will cause the profiles to be re\-read from profile files\&. This can be used to refresh the profiles without having to restart the server\&.
.RE
.PP
\'\fBsp\fR \fInnn\fR \fI@profile\fR\' \- Set profile command
.RS 4
Specify the profiles to be used on the specified recording\&. This will replace any previous defined profiles for this recording\&. Up to four profiles per recording can be defined\&.
.sp
Examples:
.sp
.if n \{\
.RS 4
.\}
.nf
sp 87 @normal @mobile
.fi
.if n \{\
.RE
.\}
.sp
Use profiles
\fInormal\fR
and
\fImobile\fR
for recording
\fI#87\fR
.RE
.SH "FILES"
.PP
Note: The system configuration directory to be used is a compile time settings and specified with the \'\fIconfiguration\fR\' argument \'\-\-sysconfdir\'\&.
.PP
/etc/X11/xawtvrc
.RS 4
A list in ini\-file format which maps the commonly known station name to a frequency channel\&. This is the default location used by the package xawtv
.RE
.PP
<log\-directory>/tvpvrd\&.log
.RS 4
The logfile\&. The log\-directory is specified in the ini\-file\&. It can also be specified as a command line argument (\fB\-l, \-\-logfile\fR) which will then override the ini\-file setting\&. By default the log file will be stored under
/tmp/tvpvrd\&.log
\&.(The reason not to use
/var/log/tvpvrd\&.log
is the fact that the server will not normally run as root and hence will not have write access to this directory\&.)
.RE
.PP
/var/run/tvpvrd\&.pid
.RS 4
The pid of the started \'tvpvrd\' server\&. This is used to easily find the pid in order to shutdown the server\&. This is used by the
\fIstop\-tvpvrd\fR
script\&. Note that in order to use this directory the daemon has to be started by the root user\&.
.RE
.PP
/etc/tvpvrd/tvpvrd\&.conf
.RS 4
Default configuration file
.RE
.PP
/etc/tvpvrd/profiles/
.RS 4
Directory with all profiles
.RE
.PP
<data\-directory>/
.RS 4
Directory where all recordings and temporary files are stored\&. The root directory is specified in the configuration file\&.
.RE
.PP
<data\-directory>/vtmp
.RS 4
Video temporary directory\&. Used to store ongoing recordings and as working directories while doing transcoding
.RE
.PP
<data\-directory>/mp2
.RS 4
If the profile specifies that the original mp2 files should be kept they are stored in this directory\&.
.RE
.PP
<data\-directory>/mp4
.RS 4
The transcoded files are stored under this folder in a subfolder with the name of the profile used for the transcoding\&.
.RE
.PP
<data\-directory>/xmldb
.RS 4
The database files are stored under this directory
.RE
.PP
<data\-directory>/stats
.RS 4
The statistics for each profile is stored in a file in XML format with the same name as the profile and with the suffix \'\&.stats\'\&.
.RE
.SH "LIMITATIONS"
.PP

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Numerical dates must be specified in European format, yyyy\-mm\-dd
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Not all international defined frequency maps are included\&. As of this writing the following maps is not yet defined in the distribution\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
us\-cable\-hrc
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
us\-cable\-irc
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
japan\-bcast
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
japan\-cable
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
china\-bcast
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
southafrica
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
argentina
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
australia\-optus
.RE
.RS 4
.sp
Frequency maps are a simple vector defining the frequency as an integer and a string that defines the channel name\&. This is a compile time setting and adding new maps will require recompilation of the server\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The
/var/run/tvpvrd\&.pid
file is not removed after the program has shut down if the effective user is any other than \'root\', (by default the server will switch to the \'tvpvrd\' user)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Maximum recording time is 4 hours (in order to keep maximum MP2 file size manageable)\&. This can result in up to ~8GB MP2 files, of course depending on the HW bitrate defined\&.
.RE
.sp
.RE
.SH "BUGS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The configuration file has too many settings\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
All information and error messages are hard coded in English and cannot be easily localized\&.
.RE
.SH "NOTES"
.PP
There is currently no graphic client but writing a basic GUI (or WEB interface) is fairly simple from a functional point of view since all necessary functionality is available via the command language\&.
.PP
Any errors that are discovered in the startup phase before a logfile has been established will be written to the default system log (normally
/var/log/messages)
.SH "RESOURCES"
.PP

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
SourceForge: <http://sourceforge\&.net/projects/tvpvrd/>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ivtv\-driver: <http://ivtvdriver\&.org/>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Video for Linux: <http://linux\&.bytesex\&.org/v4l2/>
.RE
.sp
.RE
.SH "AUTHOR"
.PP
Originally written by Johan Persson <johan162@gmail\&.com>, see the file AUTHORS for more information
.SH "COPYRIGHT"
.PP
Free use of this software is granted under the terms of the GNU General Public License (GPL v3)\&., see the file COPYING included in the distribution archive for details\&.
.SH "SEE ALSO"
.PP
\fBtvpvrd\fR(5),
\fBffmpeg\fR(1),
\fBscantv\fR(1),
\fBv4l-info\fR(1),
\fBv4l-conf\fR(1),
\fBv4lctl\fR(1),
\fBxawtv\fR(1)
.SH "AUTHOR"
.PP
\fBJohan Persson\fR <\&johan162@gmail\&.com\&>
.RS 4
Main author and maintainer
.RE
